language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r ./Asterisk-Unibo_vnfd/charms/native-charm/requirements-dev.txt
script:
  - coverage run -m unittest ./Asterisk-Unibo_vnfd/charms/native-charm/tests/test_charm.py
